### PR TITLE
rhel7-branch: firewall: add --use-system-defaults arg to command

### PR DESCRIPTION
**Pull request by dustymabe**
Needed for [1] where we would like to include firewalld
and configure firewalld in Atomic Host (in the ostree) and
have Anaconda leave the delivered "defaults" in place.

[1] https://pagure.io/atomic-wg/issue/401

(cherry picked from commit 6c2ac9500dcfc9c32e1bd329f1a0a16e8c02043b)

### CODE REVIEW

**Comment by clumens** [comment]
We'll need a bug filed with the ACKs and all that crud to get anything committed and built on rhel7-branch.

**Comment by dustymabe** [comment]
> We'll need a bug filed with the ACKs and all that crud to get anything committed and built on rhel7-branch.

like this one? https://bugzilla.redhat.com/show_bug.cgi?id=1526486

**Comment by clumens** [comment]
Yep, that'd do it.  I don't know how I missed that it was referred to in the commit message.

**Comment by clumens** [comment]
Sounds good.  On rhel7-branch, the minimal thing is usually the best thing.

**Comment by dustymabe** [comment]
changing title to WIP because we want to merge this one after the pykickstart-2 branch PR is merged.

**Comment by dustymabe** [comment]
rebased this branch and updated the commit message with the commit id from the latest commit in the pykickstart-2 PR. I want to wait for that branch to merge before we merge this branch because I want to make sure the **cherry picked from xxxx** message is right.

**Comment by dustymabe** [comment]
ok I updated the commit message - i'm going to do some final testing on el7.5 and el7.5 atomic host and then I'll give the go ahead for merge

**Comment by dustymabe** [comment]
ok testing looks good.

**Pull request merged**
