### PR TITLE
load.py initial test coverage

### PR DESCRIPTION
**Pull request by jikortus**
* The following test cases were created:
  - Load_To_String_TestCase - load content from file to string
  - Load_To_File_TestCase - load content from file to another file
  - Load_From_URL_To_Str_TestCase - load content from URL to string
  - Load_From_URL_To_File_TestCase - load content from URL to file

This is my first pull request + a few first unit tests, so any suggestions or ideas on how to improve those tests are very welcome.

### CODE REVIEW

**Comment by clumens** [comment]
Thanks for the test case!  Can you please verify that it works with PYTHON=python2 as well?  That'll get run when the python2 version of the package gets made.  I'm seeing the following traceback when I do that:

======================================================================
ERROR: runTest (tests.load.Load_To_File_TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clumens/src/pykickstart/tests/load.py", line 63, in runTest
    self.assertRaises(KickstartError, load.load_to_file, "/tmp/foo", "/tmp/bar")
  File "/usr/lib64/python2.7/unittest/case.py", line 511, in assertRaises
    callableObj(*args, **kwargs)
  File "pykickstart/load.py", line 71, in load_to_file
    _copy_file(location, destination)
  File "pykickstart/load.py", line 111, in _copy_file
    shutil.copyfile(filename, destination)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/foo'

**Comment by jikortus** [comment]
Thanks for pointing this out, I had not tried the tests explicitly with python2. The reason for the traceback was caused by the fact that IOException was raised instead of FileNotFoundError (which is derived from OSError caught even previously in _copy_file() in load.py) in python2 when a nonexistent file was opened. I fixed that in load.py (added IOExceptions to the exceptions that are caught when copying the file), I hope it is OK this way and doesn't break anything.

**Comment by clumens** [comment]
Yeah that looks good.  Thanks!  I've pushed manually to avoid the merge commit.

**Comment by jikortus** [comment]
Great, thank you!

**Pull request closed without merging**
