### PR TITLE
Update kickstart-docs.rst

### PR DESCRIPTION
**Pull request by jkonecny12**
Fix link to ksdevice to anaconda repository.

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me, but we should also remove the ``ksdevice`` docs from the kickstart documentation -- it doesn't belong there and it also has an invalid link in it.

**Comment by jkonecny12** [comment]
If it's not specifically related to this commit I think you can give me Ack a we may create new PR for the ``ksdevice`` part changes.

**Comment by vpodzime** [comment]
That's a good point. ACK.

**Comment by jkonecny12** [comment]
Pushed

**Pull request merged**
