### PR TITLE
Remove documentation compilation warnings

### PR DESCRIPTION
**Pull request by jkonecny12**
This will remove another two warnings when building documentation on anaconda.

### CODE REVIEW

**Comment by vpodzime** [comment]
The new version is really long. Is there any chance for some more compact form Sphinx would still be happy?

**Comment by jkonecny12** [comment]
I will try something to create more compact version.

**Comment by jkonecny12** [comment]
I tried do my best I hope this is enough.

**Comment by vpodzime** [comment]
Looks better to me, but I'm leaving this to @clumens to judge.

**Comment by clumens** [comment]
I don't know what kind of errors you are seeing.  I don't particularly mind the formatting of documentation one way or the other.  However, there's a lot more docstrings in pykickstart and those should probably all be in the same format, whichever one that is.

**Comment by bcl** [comment]
blivet is using keyword to document kwargs and the results look pretty good, including them in the Parameters block. eg.  :keyword clearPartType: overrides :attr:`self.config.clearPartType`

**Comment by jkonecny12** [comment]
@clumens yeah it's little harder to explain. You will see this compilation error when building docs on anaconda and it's only here because the ``AnacondaKSScript`` class (this class gets the warnings) doesn't have ``__init__()`` method so the sphinx take it from parent which is here.

@bcl I will look on that, thank you for pointing me on that

**Comment by jkonecny12** [comment]
The `keyword` is exactly what I was looking for. Thank you all for valuable input.

**Comment by jkonecny12** [comment]
Pushed. Thank you

**Pull request closed without merging**
